In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Cat-and-Dog/shop data.csv')

In [ ]:
df.shape

(22, 5)

In [ ]:
df

age  income  gender m_status  buys
0     <25    high    male   single   Bad
1     <25    high    male  married   Bad
2   25-35    high    male   single  Good
3     >35  medium    male   single  Good
4     >35     low  female   single  Good
5     >35     low  female   single   Bad
6   25-35     low  female  married  Good
7     <25  medium    male  married   Bad
8     <25     low  female   single  Good
9     >35  medium  female  married  Good
10    <25  medium  female   single  Good
11  25-35  medium    male  married  Good
12  25-35    high  female   single  Good
13    >35  medium    male  married   Bad
14    <25    high    male   single   Bad
15    <25    high  female  married  Good
16    >35  medium    male  married  Good
17    <25    high  female   single  Good
18  25-35  medium  female  married  Good
19  25-35    high    male   single  Good
20    >35  medium  female  married   Bad
21    <25     low    male   single  Good

In [ ]:
y = df.buys

In [ ]:
y

0      Bad
1      Bad
2     Good
3     Good
4     Good
5      Bad
6     Good
7      Bad
8     Good
9     Good
10    Good
11    Good
12    Good
13     Bad
14     Bad
15    Good
16    Good
17    Good
18    Good
19    Good
20     Bad
21    Good
Name: buys, dtype: object

In [ ]:
x = df.drop('buys', axis=1)

In [ ]:
x

age  income  gender m_status
0     <25    high    male   single
1     <25    high    male  married
2   25-35    high    male   single
3     >35  medium    male   single
4     >35     low  female   single
5     >35     low  female   single
6   25-35     low  female  married
7     <25  medium    male  married
8     <25     low  female   single
9     >35  medium  female  married
10    <25  medium  female   single
11  25-35  medium    male  married
12  25-35    high  female   single
13    >35  medium    male  married
14    <25    high    male   single
15    <25    high  female  married
16    >35  medium    male  married
17    <25    high  female   single
18  25-35  medium  female  married
19  25-35    high    male   single
20    >35  medium  female  married
21    <25     low    male   single

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le_x= LabelEncoder()
x = x.apply(le_x.fit_transform)

In [ ]:
x

age  income  gender  m_status
0     1       0       1         1
1     1       0       1         0
2     0       0       1         1
3     2       2       1         1
4     2       1       0         1
5     2       1       0         1
6     0       1       0         0
7     1       2       1         0
8     1       1       0         1
9     2       2       0         0
10    1       2       0         1
11    0       2       1         0
12    0       0       0         1
13    2       2       1         0
14    1       0       1         1
15    1       0       0         0
16    2       2       1         0
17    1       0       0         1
18    0       2       0         0
19    0       0       1         1
20    2       2       0         0
21    1       1       1         1

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)


In [ ]:
x_train

age  income  gender  m_status
4     2       1       0         1
2     0       0       1         1
17    1       0       0         1
6     0       1       0         0
7     1       2       1         0
1     1       0       1         0
14    1       0       1         1
0     1       0       1         1
21    1       1       1         1
20    2       2       0         0
9     2       2       0         0
8     1       1       0         1
12    0       0       0         1
11    0       2       1         0
5     2       1       0         1

In [ ]:
x_test

age  income  gender  m_status
19    0       0       1         1
16    2       2       1         0
3     2       2       1         1
13    2       2       1         0
18    0       2       0         0
15    1       0       0         0
10    1       2       0         1

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dect = DecisionTreeClassifier()
dect.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
dect.predict(x_test)

array(['Good', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Good'], dtype=object)

In [ ]:
y_test

19    Good
16    Good
3     Good
13     Bad
18    Good
15    Good
10    Good
Name: buys, dtype: object

In [ ]:
dect.score(x_test, y_test)

0.7142857142857143

In [ ]:
#Cross validation score

from sklearn.model_selection import cross_val_score

In [ ]:
result = cross_val_score(DecisionTreeClassifier(), x, y, cv=5)
result

array([0.6 , 0.6 , 0.75, 0.25, 0.5 ])

In [ ]:
result.mean()

np.float64(0.54)

In [ ]:
from sklearn.linear_model import LogisticRegression
result = cross_val_score(LogisticRegression(), x, y, cv=5)
result


array([0.4 , 0.6 , 0.75, 0.5 , 0.75])

In [ ]:
result.mean()

np.float64(0.6)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
x_scaled = MMS.fit_transform(x)
x_scaled

array([[0.5, 0. , 1. , 1. ],
       [0.5, 0. , 1. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [0. , 0.5, 0. , 0. ],
       [0.5, 1. , 1. , 0. ],
       [0.5, 0.5, 0. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 1. , 0. , 1. ],
       [0. , 1. , 1. , 0. ],
       [0. , 0. , 0. , 1. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 1. , 1. ],
       [0.5, 0. , 0. , 0. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 0. , 1. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 0.5, 1. , 1. ]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
result = cross_val_score(KNeighborsClassifier(n_neighbors=3), x_scaled, y, cv=5)
result

array([0.8 , 0.4 , 0.75, 0.5 , 0.25])

In [ ]:
result.mean()

np.float64(0.54)

In [ ]:
test = dect.predict([[2,2,1,1]])
test

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['Bad'], dtype=object)